MAIL_SYSTEM='exim'
ANTIVIRUS_SYSTEM='clamav-daemon'
ANTISPAM_SYSTEM='spamassassin'
IMAP_SYSTEM='dovecot'
DB_SYSTEM='mysql'
DB_PGSQL_SYSTEM=''
FILE_MANAGER='true'
API='yes'
LANGUAGE='en'
THEME='default'
BACKEND_PORT='8083'
HESITIA_VERSION='1.0.0'
MINIPANEL_VERSION='1.0.0'
